from colorama import Fore
import os
import main
import requests
api = "http://ip-api.com/json/"

def track():
    """Track an ip adress's global location and write the output to a file."""
    os.system("clear")
    try:
        tgt = input("Please provide the ip adress:")
        filename = input("Please provide the name for the file to save the results to.")
        data = requests.get(f"http://ip-api.com/json/{str(tgt)}")
        target = data['query']
        
        isp = data['isp']
        
        org = data['org']
        
        city = data['city']
        
        region = data['region']
        
        long = data['lon']
        
        lat = data['lat']
        
        timezone = data['timezone']
        postal_code = data['zip']
        print(f"[*] Target found {tgt}")
        print(Fore.RED + f"Information: \nTarget {target}\nISP: {isp}\nOrganization: {org}\n:City: {city}\nCountry: {region}\nPostal Code: {postal_code}\nLongtitude: {long}\nLatitude: {lat}\nTimezone: {timezone}\n")
        print(Fore.GREEN + "Writing output to file.......")
    try:
        with open(f"./Program/track_res/iptrack-{filename}.txt", 'w+') as f:
            f.write(f"IP tracker results for {tgt}\n\nTarget {target}\nISP: {isp}\nOrganization: {org}\n:City: {city}\nCountry: {region}\nPostal Code: {postal_code}\nLongtitude: {long}\nLatitude: {lat}\nTimezone: {timezone}\n" + "*" * 10 + "Generated by DokkTX. https://codechaos.net" + "*" * 10)
            print(Fore.GREEN + f"Done. Saved to Program/track_res/{filename}.txt")
            os.system("sleep 5")
            main.main()
    except Exception as e:
        print(e)